### ISSUE TITLE
The python __import__() show error. ImportError: No module named copy_reg.

### ISSUE THREAD

**Issue by guoyangji** [HongwenZhang/ECT-FaceAlignment#4]
Thanks for you sharing . I met one problem , when I ran the run_demo.py .

WARNING: Logging before InitGoogleLogging() is written to STDERR
W1026 14:04:18.403190 17798 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W1026 14:04:18.403214 17798 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W1026 14:04:18.403218 17798 _caffe.cpp:125] Net('../caffe/models/300w/matlab.prototxt', 1, weights='../model_data/')
W1026 14:04:18.404358 17798 upgrade_proto.cpp:71] Note that future Caffe releases will only support input layers and not input fields.
Traceback (most recent call last):
  File "run_demo.py", line 126, in <module>
    main(parser.parse_args())
  File "run_demo.py", line 47, in main
    fit_model = pickle.load(fit_model_file)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named copy_reg

**Comment by HongwenZhang** [comment]
Hi. This error seems to be related to the wrong version of python or something wrong with your python environment.
